trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azure-nutricode-service-connection'
  webAppName: 'appservice-nutricode'

stages:
  - stage: CI_CD
    displayName: 'CI/CD - Build e Deploy'
    jobs:
      - job: BuildAndDeploy
        displayName: 'Build e Deploy no Azure App Service'
        steps:
          - checkout: self

          - task: Maven@3
            displayName: 'Build com Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package -DskipTests'

          - task: AzureWebApp@1
            displayName: 'Deploy no Azure App Service'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(webAppName)'
              package: '$(System.DefaultWorkingDirectory)/target/*.jar'
