trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'azure-nutricode-service-connection'
  webAppName: 'appservice-nutricode'

stages:
  - stage: CI_CD
    displayName: 'CI/CD - Build e Deploy'
    jobs:
      - job: BuildAndDeploy
        displayName: 'Build e Deploy'
        steps:
          - checkout: self

          - task: Maven@3
            displayName: 'Build com Maven'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package -DskipTests'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy no Azure App Service'
            inputs:
              ConnectionType: 'PublishProfile'
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              WebAppName: '$(webAppName)'
              packageForLinux: '$(System.DefaultWorkingDirectory)/target/*.jar'
