
spring.datasource.url=jdbc:oracle:thin:@nutricodesprint3_high?TNS_ADMIN=./wallet
spring.datasource.username=ADMIN
spring.datasource.password=Nutricode123

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.application.name=nutricode


